### ISSUE TITLE
Service load order

### ISSUE THREAD

**Issue by rhamblet** [opncell/opncell#2]
Mongod needs to start first then HSS, MME/AMF, ...

**Comment by opncell** [comment]
The RC scripts have been updated to address the issue of service startup dependencies on reboot.

Changes Made:
MongoDB:

HSS has been modified to include a dependency on MongoDB.

MME/AMF services have been updated to depend on HSS. This ensures that HSS is fully operational before MME/AMF services attempt to start, resolving previous inconsistencies where MME/AMF would fail to start properly if HSS was not ready.
