### ISSUE TITLE
Subscribers not read from the Mongo DB

### ISSUE THREAD

**Issue by rhamblet** [opncell/opncell#8]
We are experiencing a problem with the subscriber feature.  When we upgraded, subscribers that were previously entered and visible in the GUI became hidden.  Checking the DB revealed they were still there.  We dumped the mongo DB then cleared the DB.  When we attempt to re-add (before and after a reboot) we get an error that the IMSI already exists:
![Screenshot 2024-07-01 at 14 30 05](https://github.com/opncell/opncell/assets/16976613/a94d93ca-ef70-4079-be16-0ca4badd6db9)
I removed the Ki and OPc from the graphic.  Could the subs be stuck in xml?

**Comment by rhamblet** [comment]
Seems removing a user didn't remove it from the /conf/config.xml  I manually edited the /conf/config.xml removed the users and resolved the "A User with this imii already exists" error

**Comment by kitandara** [comment]
Can you also share a dump of the mongo db privately.
